"""Graph manifest — the portable "what's in my graph" view + gap finder.

Reads the typed judgment nodes and emits a manifest: every value and framework, the
`embodies` edges between them (framework -> value, and the reverse value <- frameworks),
the `applies-to` coverage, and the GAPS worth filling — values no framework yet embodies,
frameworks pointing at a value-id that doesn't exist, and nodes with no applies-to (so the
lens can never select them). Read-only over the graph; never edits.

(Note: the in-vault original also scanned the broader rules corpus for opposing-directive
pairs — a rules-governance concern specific to that harness. The extracted tool's registry
is graph-focused, which is the coherent scope for a portable judgment graph.)
"""
from __future__ import annotations

import glob
import os
import re

from .config import Config


def fm_value(head, key):
    m = re.search(rf"^{re.escape(key)}:\s*(.+?)\s*$", head, re.MULTILINE)
    return m.group(1).strip().strip('\'"') if m else ""


def fm_list(head, key):
    raw = fm_value(head, key).strip("[]")
    return [x.strip().strip('\'"') for x in raw.split(",") if x.strip()] if raw else []


def load_nodes(cfg: Config):
    fm = cfg.graph.fm
    nodes = []
    for path in sorted(glob.glob(os.path.join(cfg.judgment_dir, "*.md"))):
        text = open(path, encoding="utf-8", errors="replace").read()
        head = text[3:text.find("\n---", 3)] if text.startswith("---") and text.find("\n---", 3) > 0 else text[:600]
        nid = fm_value(head, fm["id"]) or os.path.splitext(os.path.basename(path))[0]
        nodes.append({
            "id": nid,
            "name": fm_value(head, fm["name"]),
            "type": fm_value(head, fm["type"]) or "?",
            "applies_to": fm_list(head, fm["applies_to"]),
            "embodies": fm_list(head, fm["embodies"]),
            "path": os.path.relpath(path, cfg.root).replace("\\", "/"),
        })
    return nodes


def build(cfg: Config):
    nodes = load_nodes(cfg)
    by_id = {n["id"]: n for n in nodes}
    values = [n for n in nodes if n["type"] == "value"]
    frameworks = [n for n in nodes if n["type"] == "framework"]

    # value <- frameworks that embody it
    embodied_by = {v["id"]: [] for v in values}
    dangling = []  # framework -> value-id that doesn't exist
    for f in frameworks:
        for vid in f["embodies"]:
            if vid in embodied_by:
                embodied_by[vid].append(f["id"])
            elif vid in by_id:
                embodied_by.setdefault(vid, []).append(f["id"])
            else:
                dangling.append((f["id"], vid))

    coverage = sorted({t for n in nodes for t in n["applies_to"] if t != cfg.graph.baseline_tag})
    orphan_values = [v["id"] for v in values if not embodied_by.get(v["id"])]
    no_applies = [n["id"] for n in nodes if not n["applies_to"]]

    return {
        "root": cfg.root, "graph_dir": cfg.judgment_dir,
        "counts": {"total": len(nodes), "values": len(values), "frameworks": len(frameworks)},
        "values": values, "frameworks": frameworks,
        "embodied_by": embodied_by,
        "coverage": coverage,
        "gaps": {
            "values_no_framework": orphan_values,
            "frameworks_dangling_embodies": dangling,
            "nodes_no_applies_to": no_applies,
        },
    }


def manifest_md(rep) -> str:
    c = rep["counts"]
    L = ["# Judgment Graph Registry (generated)", "",
         f"> {c['total']} nodes — {c['values']} values · {c['frameworks']} frameworks. "
         "Generated by judgment-loop registry; do not edit by hand.", "",
         "## Values", "", "| Value | id | embodied by |", "|---|---|---|"]
    for v in rep["values"]:
        fw = ", ".join(rep["embodied_by"].get(v["id"], [])) or "—"
        L.append(f"| {v['name'] or v['id']} | `{v['id']}` | {fw} |")
    L += ["", "## Frameworks", "", "| Framework | id | embodies |", "|---|---|---|"]
    for f in rep["frameworks"]:
        L.append(f"| {f['name'] or f['id']} | `{f['id']}` | {', '.join(f['embodies']) or '—'} |")
    g = rep["gaps"]
    L += ["", "## Gaps", "",
          f"- **values with no framework:** {', '.join(g['values_no_framework']) or 'none'}",
          f"- **dangling embodies (framework -> missing value):** "
          f"{', '.join(f'{a}->{b}' for a, b in g['frameworks_dangling_embodies']) or 'none'}",
          f"- **nodes with no applies-to (lens can never pick them):** {', '.join(g['nodes_no_applies_to']) or 'none'}",
          "", f"## applies-to coverage ({len(rep['coverage'])} tags)", "",
          ", ".join(f"`{t}`" for t in rep["coverage"]) or "—"]
    return "\n".join(L) + "\n"
