#!/usr/bin/env python3
"""dashboard_feed.py — ONE generated, honest, current source for the Obsidian Homebase plugin.

Fixes the old dashboard's drift + false-deadness at the root: instead of the plugin hand-reading 15
state files (and computing liveness wrong), it reads this single feed, generated from the live harness:
  • Your Move   — in-motion workstreams + next-actions (from plan_brief: GOALS -> Action pillar)
  • Needs You   — decisions due review, captures to triage, RED/yellow pulse findings
  • Machine     — honest liveness (severity + the few findings that need you), small strip
Confidential lanes are surfaced as a COUNT only (never their content). 0 model tokens. Writes
.claude/_state/dashboard-data.json. Run on a cadence or on dashboard open."""
from __future__ import annotations
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

VAULT = Path(__file__).resolve().parents[2]
ROUTINES = VAULT / ".claude" / "routines"
STATE = VAULT / ".claude" / "_state"
OUT = STATE / "dashboard-data.json"
sys.path.insert(0, str(ROUTINES))


def _plan() -> dict:
    try:
        import plan_brief
        return plan_brief.build()
    except Exception:
        return {}


def _pulse() -> dict:
    try:
        d = json.loads((STATE / "harness-pulse.json").read_text(encoding="utf-8"))
        finds = [f for f in d.get("findings", []) if isinstance(f, dict) and f.get("level") in ("yellow", "red")]
        return {"severity": d.get("severity", "unknown"),
                "findings": [(f.get("code") or f.get("msg") or "finding") for f in finds][:5]}
    except Exception:
        return {"severity": "unknown", "findings": []}


def _captures() -> int:
    n = 0
    for name in ("capture-inbox.jsonl", "operate-request.jsonl"):
        p = STATE / name
        try:
            n += sum(1 for ln in p.read_text(encoding="utf-8").splitlines() if ln.strip())
        except Exception:
            pass
    return n


def build() -> dict:
    plan = _plan()
    ws = plan.get("workstreams_public", [])
    move = next((w for w in ws if w.get("next_action")), (ws[0] if ws else None))
    pulse = _pulse()
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "live_cycle": plan.get("live_cycle", ""),
        "move": ({"file": move["file"], "project": move.get("project", ""),
                  "next": move.get("next_action", ""), "okr": move.get("okr_link", "")} if move else None),
        "workstreams": [{"project": w.get("project", ""), "file": w["file"],
                         "next": w.get("next_action", ""), "status": w.get("status", "")} for w in ws[:8]],
        "needs_you": {
            "decisions_due_review": plan.get("due_reviews", []),
            "captures_to_triage": _captures(),
            "confidential_private": len(plan.get("workstreams_confidential", [])),
        },
        "machine": {"severity": pulse["severity"], "findings": pulse["findings"]},
        "launch": {"whats_the_move": "/operate what's the move",
                   "process": "/operate process this", "status": "/status"},
        "note": "generated by dashboard_feed.py — honest + current; do not hand-edit. "
                "'What's the move' (generative) = run /operate; this feed shows the queued state + machine.",
    }


def main() -> int:
    os.makedirs(OUT.parent, exist_ok=True)
    data = build()
    OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    mv = (data["move"] or {}).get("next", "—")
    print(f"dashboard feed -> {OUT}")
    print(f"  move: {mv[:60]} | workstreams: {len(data['workstreams'])} | "
          f"needs-you: {len(data['needs_you']['decisions_due_review'])} reviews, "
          f"{data['needs_you']['captures_to_triage']} captures | machine: {data['machine']['severity']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
